# Generated by Django 5.2.1 on 2025-05-15 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockeycore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='away_team_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='victor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_fixtures', to='hockeycore.team'),
        ),
    ]
