# Generated by Django 5.2.1 on 2025-05-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockeycore', '0002_fixture_away_team_score_fixture_home_team_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('D', 'Defender'), ('M', 'Midfielder'), ('F', 'Forward')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
