# Generated by Django 5.2.1 on 2025-05-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockeycore', '0003_alter_player_height_cm_alter_player_jersey_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png'),
        ),
    ]
