# Generated by Django 5.2.1 on 2025-05-22 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockeycore', '0004_player_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchevent',
            old_name='assisting_player_id',
            new_name='assisting',
        ),
        migrations.RenameField(
            model_name='matchevent',
            old_name='fixture_id',
            new_name='fixture',
        ),
        migrations.RenameField(
            model_name='matchevent',
            old_name='player_id',
            new_name='player',
        ),
        migrations.AddField(
            model_name='matchevent',
            name='card_type',
            field=models.CharField(blank=True, choices=[('yellow', 'Yellow'), ('red', 'Red')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='sub_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_in_events', to='hockeycore.player'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='sub_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_out_events', to='hockeycore.player'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('goal', 'Goal'), ('card', 'Card'), ('substitution', 'Substitution'), ('injury', 'Injury'), ('period_end', 'Period End'), ('shot', 'Shot'), ('penalty', 'Penalty')], max_length=12),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='minute',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
