# Generated by Django 5.2.1 on 2025-05-25 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockeycore', '0005_rename_assisting_player_id_matchevent_assisting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='team_id',
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_team', to='hockeycore.manager'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='card_type',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=6, null=True),
        ),
    ]
