# Generated by Django 5.2.1 on 2025-05-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hockeycore", "0005_rename_assisting_player_id_matchevent_assisting_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchevent",
            name="card_type",
            field=models.CharField(
                blank=True,
                choices=[("green", "Green"), ("yellow", "Yellow"), ("red", "Red")],
                max_length=6,
                null=True,
            ),
        ),
    ]
