# Generated by Django 5.2.1 on 2025-05-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockeycore', '0006_remove_manager_team_id_team_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='photo',
            field=models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png'),
        ),
    ]
